# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\x12\x0b\x61uthservice\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\"\x1f\n\x0b\x45xitRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"0\n\x0c\x45xitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd3\x01\n\x0b\x41uthService\x12G\n\x08Register\x12\x1c.authservice.RegisterRequest\x1a\x1d.authservice.RegisterResponse\x12>\n\x05Login\x12\x19.authservice.LoginRequest\x1a\x1a.authservice.LoginResponse\x12;\n\x04\x45xit\x12\x18.authservice.ExitRequest\x1a\x19.authservice.ExitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=35
  _globals['_REGISTERREQUEST']._serialized_end=88
  _globals['_REGISTERRESPONSE']._serialized_start=90
  _globals['_REGISTERRESPONSE']._serialized_end=142
  _globals['_LOGINREQUEST']._serialized_start=144
  _globals['_LOGINREQUEST']._serialized_end=194
  _globals['_LOGINRESPONSE']._serialized_start=196
  _globals['_LOGINRESPONSE']._serialized_end=260
  _globals['_EXITREQUEST']._serialized_start=262
  _globals['_EXITREQUEST']._serialized_end=293
  _globals['_EXITRESPONSE']._serialized_start=295
  _globals['_EXITRESPONSE']._serialized_end=343
  _globals['_AUTHSERVICE']._serialized_start=346
  _globals['_AUTHSERVICE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
