version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "50051:50051"
    depends_on:
      - mongodb
    env_file:
      - .env

  hub_service:
    build: ./hub_service
    container_name: hub_service
    ports:
      - "50052:50052"
    depends_on:
      - auth_service
    env_file:
      - .env

volumes:
  mongodbdata:
