# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_service_pb2 as chat__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.stream_stream(
                '/chatservice.ChatService/Chat',
                request_serializer=chat__service__pb2.ClientEnvelope.SerializeToString,
                response_deserializer=chat__service__pb2.ServerEnvelope.FromString,
                _registered_method=True)
        self.SubscribeChat = channel.unary_stream(
                '/chatservice.ChatService/SubscribeChat',
                request_serializer=chat__service__pb2.Init.SerializeToString,
                response_deserializer=chat__service__pb2.ServerEnvelope.FromString,
                _registered_method=True)
        self.SendChannelMsg = channel.unary_unary(
                '/chatservice.ChatService/SendChannelMsg',
                request_serializer=chat__service__pb2.ChannelMsg.SerializeToString,
                response_deserializer=chat__service__pb2.Empty.FromString,
                _registered_method=True)
        self.SendPrivateMsg = channel.unary_unary(
                '/chatservice.ChatService/SendPrivateMsg',
                request_serializer=chat__service__pb2.PrivateMsg.SerializeToString,
                response_deserializer=chat__service__pb2.Empty.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/chatservice.ChatService/GetHistory',
                request_serializer=chat__service__pb2.HistoryReq.SerializeToString,
                response_deserializer=chat__service__pb2.HistoryRes.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request_iterator, context):
        """── CLI / desktop ───────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeChat(self, request, context):
        """── Browser (gRPC-Web) ──────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChannelMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPrivateMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=chat__service__pb2.ClientEnvelope.FromString,
                    response_serializer=chat__service__pb2.ServerEnvelope.SerializeToString,
            ),
            'SubscribeChat': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeChat,
                    request_deserializer=chat__service__pb2.Init.FromString,
                    response_serializer=chat__service__pb2.ServerEnvelope.SerializeToString,
            ),
            'SendChannelMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChannelMsg,
                    request_deserializer=chat__service__pb2.ChannelMsg.FromString,
                    response_serializer=chat__service__pb2.Empty.SerializeToString,
            ),
            'SendPrivateMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPrivateMsg,
                    request_deserializer=chat__service__pb2.PrivateMsg.FromString,
                    response_serializer=chat__service__pb2.Empty.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=chat__service__pb2.HistoryReq.FromString,
                    response_serializer=chat__service__pb2.HistoryRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatservice.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chatservice.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/chatservice.ChatService/Chat',
            chat__service__pb2.ClientEnvelope.SerializeToString,
            chat__service__pb2.ServerEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chatservice.ChatService/SubscribeChat',
            chat__service__pb2.Init.SerializeToString,
            chat__service__pb2.ServerEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChannelMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatservice.ChatService/SendChannelMsg',
            chat__service__pb2.ChannelMsg.SerializeToString,
            chat__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPrivateMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatservice.ChatService/SendPrivateMsg',
            chat__service__pb2.PrivateMsg.SerializeToString,
            chat__service__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatservice.ChatService/GetHistory',
            chat__service__pb2.HistoryReq.SerializeToString,
            chat__service__pb2.HistoryRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
