# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hub_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hub_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hub_service.proto\x12\nhubservice\" \n\x0f\x45nterHubRequest\x12\r\n\x05token\x18\x01 \x01(\t\"4\n\x10\x45nterHubResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"2\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x94\x01\n\nHubService\x12\x45\n\x08\x45nterHub\x12\x1b.hubservice.EnterHubRequest\x1a\x1c.hubservice.EnterHubResponse\x12?\n\x06Logout\x12\x19.hubservice.LogoutRequest\x1a\x1a.hubservice.LogoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTERHUBREQUEST']._serialized_start=33
  _globals['_ENTERHUBREQUEST']._serialized_end=65
  _globals['_ENTERHUBRESPONSE']._serialized_start=67
  _globals['_ENTERHUBRESPONSE']._serialized_end=119
  _globals['_LOGOUTREQUEST']._serialized_start=121
  _globals['_LOGOUTREQUEST']._serialized_end=151
  _globals['_LOGOUTRESPONSE']._serialized_start=153
  _globals['_LOGOUTRESPONSE']._serialized_end=203
  _globals['_HUBSERVICE']._serialized_start=206
  _globals['_HUBSERVICE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
