# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hub_service_pb2 as hub__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hub_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HubServiceStub(object):
    """--- Service definition including the new ListChannels RPC ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnterHub = channel.unary_unary(
                '/hubservice.HubService/EnterHub',
                request_serializer=hub__service__pb2.EnterHubRequest.SerializeToString,
                response_deserializer=hub__service__pb2.EnterHubResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/hubservice.HubService/Logout',
                request_serializer=hub__service__pb2.LogoutRequest.SerializeToString,
                response_deserializer=hub__service__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.ListChannels = channel.unary_unary(
                '/hubservice.HubService/ListChannels',
                request_serializer=hub__service__pb2.Empty.SerializeToString,
                response_deserializer=hub__service__pb2.ChannelListResponse.FromString,
                _registered_method=True)


class HubServiceServicer(object):
    """--- Service definition including the new ListChannels RPC ---
    """

    def EnterHub(self, request, context):
        """Verifies the token and grants access to the central hub
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logs the user out by invalidating the token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChannels(self, request, context):
        """New RPC: return the list of all available channels
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HubServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnterHub': grpc.unary_unary_rpc_method_handler(
                    servicer.EnterHub,
                    request_deserializer=hub__service__pb2.EnterHubRequest.FromString,
                    response_serializer=hub__service__pb2.EnterHubResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=hub__service__pb2.LogoutRequest.FromString,
                    response_serializer=hub__service__pb2.LogoutResponse.SerializeToString,
            ),
            'ListChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChannels,
                    request_deserializer=hub__service__pb2.Empty.FromString,
                    response_serializer=hub__service__pb2.ChannelListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hubservice.HubService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hubservice.HubService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HubService(object):
    """--- Service definition including the new ListChannels RPC ---
    """

    @staticmethod
    def EnterHub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hubservice.HubService/EnterHub',
            hub__service__pb2.EnterHubRequest.SerializeToString,
            hub__service__pb2.EnterHubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hubservice.HubService/Logout',
            hub__service__pb2.LogoutRequest.SerializeToString,
            hub__service__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hubservice.HubService/ListChannels',
            hub__service__pb2.Empty.SerializeToString,
            hub__service__pb2.ChannelListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
