syntax = "proto3";
package hubservice;

message Empty          {}
message Channel        { string id = 1; string name = 2; }
message ChannelListRes { repeated Channel channels = 1; }

message CreateReq      { string name = 1; }
message DeleteReq      { string id   = 1; }
message BoolRes        { bool   ok   = 1; string message = 2; }

message EnterHubReq    { string token = 1; }
message EnterHubRes    { bool success = 1; string message = 2; }
message LogoutReq      { string token = 1; }
message LogoutRes      { bool success = 1; string message = 2; }

service HubService {
  rpc EnterHub     (EnterHubReq)  returns (EnterHubRes);
  rpc Logout       (LogoutReq)    returns (LogoutRes);

  rpc ListChannels (Empty)        returns (ChannelListRes);
  rpc CreateChannel(CreateReq)    returns (BoolRes);
  rpc DeleteChannel(DeleteReq)    returns (BoolRes);
}
