# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hub_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hub_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11hub_service.proto\x12\nhubservice\"\x07\n\x05\x45mpty\"#\n\x07\x43hannel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"7\n\x0e\x43hannelListRes\x12%\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x13.hubservice.Channel\"\x19\n\tCreateReq\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x17\n\tDeleteReq\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x07\x42oolRes\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x0b\x45nterHubReq\x12\r\n\x05token\x18\x01 \x01(\t\"/\n\x0b\x45nterHubRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1a\n\tLogoutReq\x12\r\n\x05token\x18\x01 \x01(\t\"-\n\tLogoutRes\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbb\x02\n\nHubService\x12<\n\x08\x45nterHub\x12\x17.hubservice.EnterHubReq\x1a\x17.hubservice.EnterHubRes\x12\x36\n\x06Logout\x12\x15.hubservice.LogoutReq\x1a\x15.hubservice.LogoutRes\x12=\n\x0cListChannels\x12\x11.hubservice.Empty\x1a\x1a.hubservice.ChannelListRes\x12;\n\rCreateChannel\x12\x15.hubservice.CreateReq\x1a\x13.hubservice.BoolRes\x12;\n\rDeleteChannel\x12\x15.hubservice.DeleteReq\x1a\x13.hubservice.BoolResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=33
  _globals['_EMPTY']._serialized_end=40
  _globals['_CHANNEL']._serialized_start=42
  _globals['_CHANNEL']._serialized_end=77
  _globals['_CHANNELLISTRES']._serialized_start=79
  _globals['_CHANNELLISTRES']._serialized_end=134
  _globals['_CREATEREQ']._serialized_start=136
  _globals['_CREATEREQ']._serialized_end=161
  _globals['_DELETEREQ']._serialized_start=163
  _globals['_DELETEREQ']._serialized_end=186
  _globals['_BOOLRES']._serialized_start=188
  _globals['_BOOLRES']._serialized_end=226
  _globals['_ENTERHUBREQ']._serialized_start=228
  _globals['_ENTERHUBREQ']._serialized_end=256
  _globals['_ENTERHUBRES']._serialized_start=258
  _globals['_ENTERHUBRES']._serialized_end=305
  _globals['_LOGOUTREQ']._serialized_start=307
  _globals['_LOGOUTREQ']._serialized_end=333
  _globals['_LOGOUTRES']._serialized_start=335
  _globals['_LOGOUTRES']._serialized_end=380
  _globals['_HUBSERVICE']._serialized_start=383
  _globals['_HUBSERVICE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
